### ISSUE TITLE
UIItem getItem, empty string on getName and getDescription

### ISSUE THREAD

**Issue by Oen44** [otland/otclient#15]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Inside modules/game_interface/widgets/uiitem.lua in `UIItem:onHoverChange` method add `print(self:getItem():getName())`
2. Launch client, reload game_interface module if needed
3. Hover over any item in inventory or container, open Terminal (CTRL+T) to check if anything got printed, blank line will appear instead of item name

### Expected behaviour
When getting item from UIItem (getItem() returns Item object) and accessing getName() method, item name should be returned.

### Actual behaviour
Empty string is returned, same with getDescription() and other methods.

I'd like to add that getCount() and getId() returns proper values.

### Environment
OTClient 0.6.6, protocol 8.6 and 10.98.

**Comment by 4drik** [comment]
I just tested getId() and it works (ofc with clientId, not serverId).
getDescription() and getName() don't work because the server does not send this information about the item. This information is sent in the form of a string only after using the look.

To make this work, you need to make changes to TFS and OTC.
In OTC in function getItem you need to add setItemDescription(msg->getString()); and the same with name. If you need serverId you can also set it with itemType->setServerId(x). Then ofc, you can get it with getServerId() function in lua too, because it's binded.

In TFS you have to send the string and int in the same order as you added to OTC in NetworkMessage::addItem function.

**Comment by EgzoT** [comment]
This information you get after load items information from items files (you find it in server files).

g_things.loadOtb('items.otb')
g_things.loadXml('items.xml') 

So this is not bug. Issue to close.

**Comment by Oen44** [comment]
Thank you for the correction.
